### ISSUE TITLE
The repeated answers are counted as answers for new questions

### ISSUE THREAD

**Issue by nkostyanetskaya** [redrick-tmn/ikea-quiz-bot#7]
- Start the game
- Click on the button with an answer several times: 

![image](https://cloud.githubusercontent.com/assets/18097936/19680275/bb1cfcaa-9aad-11e6-9b69-e5ad8960fb03.png)

Actual result: The repeated answers are counted as answers for the new questions (the pictures are not loaded)
Expected result: The repeated answer is counted for a question on;y after picture&question loading

**Comment by dmitriy-kostianetskiy** [comment]
Common behavior for most bots. No further actions.
